DROP TABLE G_MEMBER;
DROP SEQUENCE g_member_no_seq;

DROP TABLE G_GAME;

DROP TABLE G_PLAYLOG;
DROP SEQUENCE g_playlog_no_seq;

DROP TABLE G_BADGE;
DROP SEQUENCE g_badge_no_seq;

DROP TABLE G_NOTICE;
DROP SEQUENCE g_notice_no_seq;

DROP TABLE G_QUESTION;
DROP SEQUENCE g_question_no_seq;
